services:
  web:
    command: ["devserver"]         # runserver con autoreload in dev
    volumes:
      - ./:/app:cached
      - staticfiles:/app/staticfiles
      - media:/app/media
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECURE_SSL_REDIRECT: "0"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost,http://127.0.0.1,http://localhost:8080,http://127.0.0.1:8080

  nginx:
    ports:
      - "8080:80"  # così tieni libero 80 se ti serve
