services:
  web:
    # niente "command" qui: il nostro entrypoint userà DJANGO_DEBUG=1 per runserver
    volumes:
      - ./:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
      - ./data:/app/data:ro        # <— anche in dev montiamo i CSV
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECURE_SSL_REDIRECT: "0"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost,http://127.0.0.1,http://localhost:8080,http://127.0.0.1:8080
      SEED_ON_START: "true"        # <— seed automatico anche in dev

  nginx:
    ports:
      - "8080:80"
