# Generated by Django 5.2.6 on 2025-09-18 14:43

import core.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_for_approval', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('modifiable', models.BooleanField(default=True)),
                ('response_text', models.CharField(max_length=3)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('textarea', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('transliteration', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_full', models.CharField(max_length=255)),
                ('position', models.IntegerField(unique=True)),
                ('grp', models.CharField(blank=True, max_length=255, null=True)),
                ('isocode', models.CharField(blank=True, max_length=50, null=True)),
                ('glottocode', models.CharField(blank=True, max_length=50, null=True)),
                ('informant', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.language'),
        ),
        migrations.CreateModel(
            name='LanguageParameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_orig', models.CharField(max_length=1)),
                ('warning_orig', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_parameters', to='core.language')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageParameterEval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_eval', models.CharField(max_length=1)),
                ('warning_eval', models.BooleanField(default=False)),
                ('language_parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval', to='core.languageparameter')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerMotivation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_motivations', to='core.answer')),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answer_motivations', to='core.motivation')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterDef',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('implicational_condition', models.TextField(blank=True, null=True)),
                ('warning_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['position'], name='core_parame_positio_b97822_idx')],
            },
        ),
        migrations.AddField(
            model_name='languageparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='language_parameters', to='core.parameterdef'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('example_yes', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('template_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_stop_question', models.BooleanField(default=False)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questions', to='core.parameterdef')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answers', to='core.question'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('ruleset_version', models.TextField(blank=True, null=True)),
                ('algo_code_hash', models.TextField(blank=True, null=True)),
                ('param_def_checksum', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='core.language')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=40)),
                ('response_text', models.CharField(max_length=3)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnswerMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=40)),
                ('motivation_code', models.CharField(max_length=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_motivations', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionExample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_code', models.CharField(max_length=40)),
                ('textarea', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('transliteration', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', models.CharField(max_length=20)),
                ('value_orig', models.CharField(max_length=1)),
                ('warning_orig', models.BooleanField(default=False)),
                ('value_eval', models.CharField(max_length=1)),
                ('warning_eval', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='core.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uq_user_email_lower'),
        ),
        migrations.AddIndex(
            model_name='example',
            index=models.Index(fields=['answer'], name='core_exampl_answer__4d5526_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['position'], name='core_langua_positio_7a53da_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['assigned_user'], name='core_langua_assigne_af4f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='languageparametereval',
            constraint=models.CheckConstraint(condition=models.Q(('value_eval__in', ['+', '-', '0'])), name='ck_value_eval_pm0'),
        ),
        migrations.AddIndex(
            model_name='answermotivation',
            index=models.Index(fields=['answer'], name='core_answer_answer__3ccb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='answermotivation',
            index=models.Index(fields=['motivation'], name='core_answer_motivat_fad45f_idx'),
        ),
        migrations.AddConstraint(
            model_name='answermotivation',
            constraint=models.UniqueConstraint(fields=('answer', 'motivation'), name='uq_answer_motivation'),
        ),
        migrations.AddIndex(
            model_name='languageparameter',
            index=models.Index(fields=['language'], name='core_langua_languag_60f455_idx'),
        ),
        migrations.AddIndex(
            model_name='languageparameter',
            index=models.Index(fields=['parameter'], name='core_langua_paramet_60df17_idx'),
        ),
        migrations.AddConstraint(
            model_name='languageparameter',
            constraint=models.UniqueConstraint(fields=('language', 'parameter'), name='uq_lang_param'),
        ),
        migrations.AddConstraint(
            model_name='languageparameter',
            constraint=models.CheckConstraint(condition=models.Q(('value_orig__in', ['+', '-'])), name='ck_value_orig_pm'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['parameter'], name='core_questi_paramet_721f34_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['parameter', 'is_stop_question'], name='core_questi_paramet_0a9c17_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['language'], name='core_answer_languag_ceec47_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='core_answer_questio_30e282_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('language', 'question'), name='uq_answer_lang_q'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('response_text__in', ['yes', 'no'])), name='ck_answer_resp_yesno'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modifiable', True), ('status__in', ['pending', 'rejected'])), models.Q(('modifiable', False), ('status__in', ['waiting_for_approval', 'approved'])), _connector='OR'), name='ck_answer_status_modifiable'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['language'], name='core_submis_languag_8a2ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_by'], name='core_submis_submitt_92b3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='core_submis_submitt_cc7493_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionanswer',
            index=models.Index(fields=['submission', 'question_code'], name='core_submis_submiss_0b04a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question_code'), name='pk_submission_answer'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswer',
            constraint=models.CheckConstraint(condition=models.Q(('response_text__in', ['yes', 'no'])), name='ck_sub_answer_yesno'),
        ),
        migrations.AddIndex(
            model_name='submissionanswermotivation',
            index=models.Index(fields=['submission', 'question_code'], name='core_submis_submiss_3a25c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionanswermotivation',
            constraint=models.UniqueConstraint(fields=('submission', 'question_code', 'motivation_code'), name='pk_submission_answer_motivation'),
        ),
        migrations.AddIndex(
            model_name='submissionexample',
            index=models.Index(fields=['submission', 'question_code'], name='core_submis_submiss_4f3f48_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionparam',
            index=models.Index(fields=['submission', 'parameter_id'], name='core_submis_submiss_1cc4c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.UniqueConstraint(fields=('submission', 'parameter_id'), name='pk_submission_param'),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(condition=models.Q(('value_orig__in', ['+', '-', '0'])), name='ck_sub_param_orig'),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(condition=models.Q(('value_eval__in', ['+', '-', '0'])), name='ck_sub_param_eval'),
        ),
    ]
