# Generated by Django 5.2.5 on 2025-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parameterdef',
            name='core_parame_positio_b97822_idx',
        ),
        migrations.RemoveField(
            model_name='parameterdef',
            name='warning_default',
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='implicational_condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
