# Generated by Django 5.2.6 on 2025-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_parameterdef_core_parame_positio_b97822_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdef',
            name='implicational_condition',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
