# Generated by Django 5.2.6 on 2025-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_parameterdef_implicational_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdef',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
