# Generated by Django 5.2.6 on 2025-09-22 09:36

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parameterdef_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdef',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='parameterdef',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('position',), name='uniq_parameterdef_position_deferrable'),
        ),
    ]
