# Generated by Django 5.2.6 on 2025-09-22 12:25

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parameterdef_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('position',), name='uniq_language_position_deferrable'),
        ),
    ]
