# Generated by Django 5.2.6 on 2025-09-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_language_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='m2m_languages',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.language'),
        ),
    ]
