# Generated by Django 5.2.5 on 2025-09-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_m2m_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAllowedMotivation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=1)),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allowed_for_questions', to='core.motivation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_motivations', to='core.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question'], name='core_questi_questio_4f294a_idx'), models.Index(fields=['motivation'], name='core_questi_motivat_1244e6_idx'), models.Index(fields=['question', 'position'], name='core_questi_questio_faec1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'motivation'), name='uq_question_allowed_motivation')],
            },
        ),
    ]
