# Generated by Django 5.2.5 on 2025-09-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_questionallowedmotivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allowed_motivations',
            field=models.ManyToManyField(blank=True, related_name='questions_allowed', through='core.QuestionAllowedMotivation', to='core.motivation'),
        ),
        migrations.AlterField(
            model_name='questionallowedmotivation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_motivation_links', to='core.question'),
        ),
    ]
