# Generated by Django 5.2.5 on 2025-10-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_allowed_motivations_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='languageparameter',
            name='ck_value_orig_pm',
        ),
        migrations.AlterField(
            model_name='languageparameter',
            name='value_orig',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='languageparameter',
            constraint=models.CheckConstraint(condition=models.Q(('value_orig__in', ['+', '-']), ('value_orig__isnull', True), _connector='OR'), name='ck_value_orig_pm_or_null'),
        ),
    ]
