# Generated by Django 5.2.7 on 2025-10-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_languagereview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissionparam',
            name='ck_sub_param_orig',
        ),
        migrations.AlterField(
            model_name='submissionparam',
            name='value_orig',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(condition=models.Q(('value_orig__in', ['+', '-', '0']), ('value_orig__isnull', True), _connector='OR'), name='ck_sub_param_orig'),
        ),
    ]
