# Generated by Django 5.2.5 on 2025-10-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_submissionparam_ck_sub_param_orig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recap', models.TextField()),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_change_logs', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.parameterdef')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['changed_at'], name='core_parame_changed_69f1fb_idx'), models.Index(fields=['parameter'], name='core_parame_paramet_55adae_idx'), models.Index(fields=['changed_by'], name='core_parame_changed_fa9bd2_idx')],
            },
        ),
    ]
