# Generated by Django 5.2.7 on 2025-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_ck_answer_status_modifiable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='ck_answer_status_modifiable',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('modifiable', True), ('status__in', ['pending'])), models.Q(('modifiable', False), ('status__in', ['waiting_for_approval', 'approved', 'rejected'])), _connector='OR'), name='ck_answer_status_modifiable'),
        ),
    ]
