# Generated by Django 5.2.5 on 2025-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_languageparametereval_ck_value_eval_pm0_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissionparam',
            name='pk_submission_param',
        ),
        migrations.RemoveConstraint(
            model_name='submissionparam',
            name='ck_sub_param_eval',
        ),
        migrations.RemoveConstraint(
            model_name='submissionparam',
            name='ck_sub_param_orig',
        ),
        migrations.RemoveIndex(
            model_name='submissionparam',
            name='core_submis_submiss_1cc4c3_idx',
        ),
        migrations.AlterField(
            model_name='submissionparam',
            name='value_eval',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('0', '0')], max_length=1, null=True),
        ),
    ]
