# Generated by Django 5.2.7 on 2025-10-18 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_answer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParameterReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to='core.language')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to='core.parameterdef')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'user'], name='core_parame_languag_5882ba_idx'), models.Index(fields=['parameter'], name='core_parame_paramet_d0a9ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('language', 'parameter', 'user'), name='uq_reviewflag_lang_param_user')],
            },
        ),
    ]
