# Generated by Django 5.2.7 on 2025-10-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_question_help_info_parameterreviewflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ParamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['position', 'code'],
            },
        ),
        migrations.AddField(
            model_name='parameterdef',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='core.paramschema'),
        ),
        migrations.AddField(
            model_name='parameterdef',
            name='param_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='core.paramtype'),
        ),
    ]
