# Generated by Django 5.2.7 on 2025-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_paramschema_paramtype_parameterdef_schema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paramschema',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='paramtype',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='paramschema',
            name='position',
        ),
        migrations.RemoveField(
            model_name='paramtype',
            name='position',
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='param_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parameterdef',
            name='schema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paramschema',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paramtype',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
