# Generated by Django 5.2.7 on 2025-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_paramschema_options_alter_paramtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paramschema',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='paramtype',
            options={'ordering': ['label']},
        ),
        migrations.RemoveField(
            model_name='paramschema',
            name='code',
        ),
        migrations.RemoveField(
            model_name='paramschema',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paramtype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='paramtype',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='paramschema',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paramtype',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
