# Generated by Django 5.2.7 on 2025-10-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_paramschema_options_alter_paramtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='historical_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='language',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='top_level_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['family'], name='core_langua_family_c34868_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['top_level_family'], name='core_langua_top_lev_75e344_idx'),
        ),
    ]
