# Generated by Django 5.2.7 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.functions.text


def drop_old_pk_and_add_id(apps, schema_editor):
    """
    Migrazione robusta/idempotente:
    - Se esiste ancora una PK sulla tabella (di solito su word), la droppa.
    - Se la colonna id non esiste, la crea come BIGSERIAL.
    - Si assicura che id sia NOT NULL.
    - Imposta la nuova PK su id se non già presente.
    """

    # 0. Nome tabella
    table = "core_glossary"

    # 1. recupera info su:
    #    - pk constraint attuale (se c'è)
    #    - se la colonna id esiste
    with schema_editor.connection.cursor() as cursor:
        # trova la PK attuale
        cursor.execute(
            """
            SELECT conname, pg_get_constraintdef(pc.oid)
            FROM pg_constraint pc
            JOIN pg_class c ON pc.conrelid = c.oid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = %s
              AND n.nspname = 'public'
              AND pc.contype = 'p'
            LIMIT 1;
            """,
            [table],
        )
        pk_row = cursor.fetchone()
        current_pk_name = pk_row[0] if pk_row else None
        current_pk_def = pk_row[1] if pk_row else ""  # es: 'PRIMARY KEY (word)' oppure '(id)'

        # controlla se la colonna id esiste già
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
              AND column_name = 'id';
            """,
            [table],
        )
        id_exists = cursor.fetchone() is not None

    # 2. se la pk attuale NON è già su ("id"), la dropperemo più tardi
    pk_is_already_id = "id" in current_pk_def

    # 3. se la colonna id non esiste ancora -> creala
    if not id_exists:
        # aggiungi colonna id BIGSERIAL
        schema_editor.execute(
            f'ALTER TABLE "{table}" ADD COLUMN "id" BIGSERIAL;'
        )

    # 4. forza NOT NULL su id (se già NOT NULL, Postgres non si lamenta)
    schema_editor.execute(
        f'ALTER TABLE "{table}" ALTER COLUMN "id" SET NOT NULL;'
    )

    # 5. se la PK NON è già su id:
    #    - droppa la vecchia PK
    #    - crea la nuova PK su id
    if not pk_is_already_id and current_pk_name:
        # drop vecchia PK (su word)
        schema_editor.execute(
            f'ALTER TABLE "{table}" DROP CONSTRAINT "{current_pk_name}";'
        )
        # crea nuova PK su id
        schema_editor.execute(
            f'ALTER TABLE "{table}" ADD CONSTRAINT "core_glossary_pkey" PRIMARY KEY ("id");'
        )
    elif not pk_is_already_id and not current_pk_name:
        # caso estremo: non c'è pk per qualche motivo, la creiamo comunque su id
        schema_editor.execute(
            f'ALTER TABLE "{table}" ADD CONSTRAINT "core_glossary_pkey" PRIMARY KEY ("id");'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_language_family_language_historical_language_and_more'),
    ]

    operations = [
        # Fase SQL personalizzata per migrare da word->id come PK
        migrations.RunPython(drop_old_pk_and_add_id, migrations.RunPython.noop),

        # Aggiorniamo il campo word nello "state" Django
        migrations.AlterField(
            model_name='glossary',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),

        # Diciamo allo state di Django che esiste 'id' come BigAutoField primary_key=True
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='glossary',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                # db già cambiato sopra
            ],
        ),

        # Vincolo case-insensitive su word
        migrations.AddConstraint(
            model_name='glossary',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('word'),
                name='uq_glossary_word_lower',
            ),
        ),

        # Parte SubmissionParam (come nella tua 0024 originale)
        migrations.AddIndex(
            model_name='submissionparam',
            index=models.Index(
                fields=['submission', 'parameter_id'],
                name='core_submis_submiss_1cc4c3_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.UniqueConstraint(
                fields=('submission', 'parameter_id'),
                name='pk_submission_param',
            ),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('value_orig__in', ['+', '-', '0']),
                    ('value_orig__isnull', True),
                    _connector='OR'
                ),
                name='ck_sub_param_orig',
            ),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('value_eval__in', ['+', '-', '0']),
                    ('value_eval__isnull', True),
                    _connector='OR'
                ),
                name='ck_sub_param_eval',
            ),
        ),
    ]
