# Generated by Django 5.2.7 on 2025-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_glossary_id_alter_glossary_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction_yes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
