# Generated by Django 5.2.7 on 2025-11-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_question_instruction_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.language'),
        ),
    ]
