# Generated by Django 5.2.7 on 2025-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
