# Generated by Django 5.2.7 on 2025-11-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_question_example_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='example_no',
            new_name='instuction_no',
        ),
    ]
