# Generated by Django 5.2.7 on 2025-11-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_example_no_question_instuction_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='instuction_no',
            new_name='instruction_no',
        ),
    ]
