# Generated by Django 5.2.8 on 2025-11-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_instuction_no_question_instruction_no'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['language', 'status'], name='core_answer_languag_a192a4_idx'),
        ),
        migrations.AddIndex(
            model_name='languagereview',
            index=models.Index(fields=['language', 'created_at'], name='core_langua_languag_321fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='languagereview',
            index=models.Index(fields=['language', 'decision', 'created_at'], name='core_langua_languag_62fa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['language', 'submitted_at'], name='core_submis_languag_783d58_idx'),
        ),
    ]
