# Generated by Django 5.2.9 on 2026-01-05 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_answer_core_answer_languag_a192a4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
