# Generated by Django 5.2.11 on 2026-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_language_latitude_language_longitude_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamLevelOfComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='parameterdef',
            name='level_of_comparison',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
