# Generated by Django 5.2.11 on 2026-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_paramlevelofcomparison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
