# Generated by Django 5.2.11 on 2026-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_language_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdef',
            name='description_of_the_implicational_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parameterdef',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
