# Generated by Django 5.2.11

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_terms_accepted_user_terms_accepted_at'),
    ]

    operations = [
        # --- SITE CONTENT: Saltiamo la creazione perché la tabella esiste già ---
        # migrations.CreateModel(
        #     name='SiteContent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('key', models.CharField(help_text="Identificativo univoco del blocco.", max_length=100, unique=True)),
        #         ('page', models.CharField(blank=True, default='', max_length=50)),
        #         ('content', models.TextField(blank=True, default='')),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'ordering': ['page', 'key'],
        #     },
        # ),

        # --- LANGUAGE PARAMETER EVAL: Abilitazione del simbolo '?' ---
        migrations.RemoveConstraint(
            model_name='languageparametereval',
            name='ck_value_eval_pm0_or_null',
        ),
        migrations.AlterField(
            model_name='languageparametereval',
            name='value_eval',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('0', '0'), ('?', '?')], help_text="Valore valutato dal DAG: '+', '-', '0' oppure '?' .", max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='languageparametereval',
            constraint=models.CheckConstraint(check=models.Q(('value_eval__in', ['+', '-', '0', '?']), ('value_eval__isnull', True), _connector='OR'), name='ck_value_eval_pm0_or_null'),
        ),

        # --- SUBMISSION PARAM: Abilitazione del simbolo '?' ---
        migrations.RemoveConstraint(
            model_name='submissionparam',
            name='ck_sub_param_orig',
        ),
        migrations.RemoveConstraint(
            model_name='submissionparam',
            name='ck_sub_param_eval',
        ),
        migrations.AlterField(
            model_name='submissionparam',
            name='value_eval',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('0', '0'), ('?', '?')], max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(check=models.Q(('value_orig__in', ['+', '-', '0', '?']), ('value_orig__isnull', True), _connector='OR'), name='ck_sub_param_orig'),
        ),
        migrations.AddConstraint(
            model_name='submissionparam',
            constraint=models.CheckConstraint(check=models.Q(('value_eval__in', ['+', '-', '0', '?']), ('value_eval__isnull', True), _connector='OR'), name='ck_sub_param_eval'),
        ),
    ]